# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 791)
        MainWindow.setStyleSheet("/* Общий стиль для окна */\n"
"QWidget {\n"
"    background-color: white; /* Белый фон */\n"
"    color: #1E90FF; /* Светло-синий текст */\n"
"}\n"
"\n"
"/* Стиль для кнопок */\n"
"QPushButton {\n"
"    background-color: #1E90FF; /* Светло-синий */\n"
"    color: white; /* Белый текст */\n"
"    border: 2px solid #1E90FF;\n"
"    padding: 5px 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4682B4; /* Тесно-синий при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0D47A1; /* Темно-синий при нажатии */\n"
"}\n"
"\n"
"/* Стиль для меток */\n"
"QLabel {\n"
"    color: #1E90FF; /* Светло-синий текст */\n"
"}\n"
"\n"
"/* Стиль для полей ввода */\n"
"QLineEdit {\n"
"    background-color: white; /* Белый фон */\n"
"    color: #1E90FF; /* Светло-синий текст */\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid #4682B4; /* Тесно-синий при наведении */\n"
"}\n"
"\n"
"/* Стиль для списка */\n"
"QListWidget {\n"
"    background-color: white; /* Белый фон */\n"
"    color: #1E90FF; /* Светло-синий текст */\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QListWidget:hover {\n"
"    border: 2px solid #4682B4; /* Тесно-синий при наведении */\n"
"}\n"
"\n"
"/* Стиль для таблицы */\n"
"QTableWidget {\n"
"    background-color: white; /* Белый фон */\n"
"    color: #1E90FF; /* Светло-синий текст */\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTableWidget:hover {\n"
"    border: 2px solid #4682B4; /* Тесно-синий при наведении */\n"
"}\n"
"\n"
"/* Стиль для комбо-бокса */\n"
"QComboBox {\n"
"    background-color: white; /* Белый фон */\n"
"    color: #1E90FF; /* Светло-синий текст */\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #4682B4; /* Тесно-синий при наведении */\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    background-color: #0D47A1; /* Темно-синий при нажатии */\n"
"    border: 2px solid #0D47A1;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("font: 16pt \"Ubuntu Mono\";")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setMinimumSize(QtCore.QSize(350, 100))
        self.frame.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(340, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(340, 40))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(340, 40))
        self.label_2.setMaximumSize(QtCore.QSize(340, 40))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(350, 610))
        self.frame_5.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.listWidget = QtWidgets.QListWidget(self.frame_5)
        self.listWidget.setMaximumSize(QtCore.QSize(340, 16777200))
        self.listWidget.setStyleSheet("font: 12pt \"Ubuntu Mono\";")
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.horizontalLayout_5.addWidget(self.listWidget)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setMinimumSize(QtCore.QSize(660, 730))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(660, 200))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_3.setStyleSheet("font: 12pt \"Ubuntu Mono\";")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_12.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_12.setSpacing(2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget.setMinimumSize(QtCore.QSize(661, 131))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 131))
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_12.addWidget(self.tableWidget)
        self.spinBox = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox.setMinimumSize(QtCore.QSize(661, 31))
        self.spinBox.setMaximumSize(QtCore.QSize(16777215, 31))
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_12.addWidget(self.spinBox)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(660, 530))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame_4)
        self.tabWidget_2.setEnabled(True)
        self.tabWidget_2.setStyleSheet("font: 14pt \"Ubuntu Mono\";")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.tab_3)
        self.widget.setObjectName("widget")
        self.verticalLayout_4.addWidget(self.widget)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.tab_4)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4.addWidget(self.widget_2)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.tab_5)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3.addWidget(self.widget_3)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.tab_6)
        self.openGLWidget.setEnabled(False)
        self.openGLWidget.setObjectName("openGLWidget")
        self.verticalLayout_2.addWidget(self.openGLWidget)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.horizontalLayout_3.addWidget(self.tabWidget_2)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setContentsMargins(2, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_7 = QtWidgets.QFrame(self.page)
        self.frame_7.setMinimumSize(QtCore.QSize(1020, 40))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setMinimumSize(QtCore.QSize(900, 40))
        self.label_3.setMaximumSize(QtCore.QSize(65556, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_2.setMinimumSize(QtCore.QSize(115, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(115, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_8.addWidget(self.pushButton_2)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.page)
        self.frame_6.setMinimumSize(QtCore.QSize(1020, 200))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget_2.setStyleSheet("font: 12pt \"Ubuntu Mono\";")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(17)
        self.tableWidget_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 12, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(35)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(35)
        self.horizontalLayout_6.addWidget(self.tableWidget_2)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setContentsMargins(1, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_8 = QtWidgets.QFrame(self.page_2)
        self.frame_8.setMinimumSize(QtCore.QSize(1020, 40))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setMinimumSize(QtCore.QSize(900, 40))
        self.label_4.setMaximumSize(QtCore.QSize(65556, 40))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_3.setMinimumSize(QtCore.QSize(115, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(115, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_9.addWidget(self.pushButton_3)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget_3.setStyleSheet("font: 14pt \"Ubuntu Mono\";")
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.comboBox = QtWidgets.QComboBox(self.tab_7)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.verticalLayout_8.addWidget(self.comboBox)
        self.widget_4 = QtWidgets.QWidget(self.tab_7)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_8.addWidget(self.widget_4)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_8)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.verticalLayout_9.addWidget(self.comboBox_2)
        self.VTKFrame = QtWidgets.QFrame(self.tab_8)
        self.VTKFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VTKFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VTKFrame.setObjectName("VTKFrame")
        self.verticalLayout_9.addWidget(self.VTKFrame)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.verticalLayout_7.addWidget(self.tabWidget_3)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_10.setContentsMargins(2, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_9 = QtWidgets.QFrame(self.page_3)
        self.frame_9.setMinimumSize(QtCore.QSize(1020, 40))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.frame_9)
        self.label_5.setMinimumSize(QtCore.QSize(900, 40))
        self.label_5.setMaximumSize(QtCore.QSize(65556, 40))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_4.setMinimumSize(QtCore.QSize(115, 40))
        self.pushButton_4.setMaximumSize(QtCore.QSize(115, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_10.addWidget(self.pushButton_4)
        self.verticalLayout_10.addWidget(self.frame_9)
        self.comboBox_3 = QtWidgets.QComboBox(self.page_3)
        self.comboBox_3.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.verticalLayout_10.addWidget(self.comboBox_3)
        self.frame_10 = QtWidgets.QFrame(self.page_3)
        self.frame_10.setStyleSheet("font: 16pt \"Ubuntu Mono\";")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_10)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1901, 1061))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(0, 30, 1191, 121))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 270, 31))
        self.lineEdit.setMinimumSize(QtCore.QSize(270, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(270, 16777215))
        self.lineEdit.setStyleSheet("font: 12pt \"Ubuntu Mono\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 70, 270, 31))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(270, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(270, 16777215))
        self.lineEdit_2.setStyleSheet("font: 12pt \"Ubuntu Mono\";")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.frame_11 = QtWidgets.QFrame(self.groupBox)
        self.frame_11.setGeometry(QtCore.QRect(290, 30, 270, 35))
        self.frame_11.setMinimumSize(QtCore.QSize(270, 35))
        self.frame_11.setMaximumSize(QtCore.QSize(270, 35))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.frame_11)
        self.label_6.setMinimumSize(QtCore.QSize(150, 30))
        self.label_6.setStyleSheet("font: 12pt \"Ubuntu Mono\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_11)
        self.comboBox_4.setMinimumSize(QtCore.QSize(100, 30))
        self.comboBox_4.setStyleSheet("font: 10pt \"Ubuntu Mono\";")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(570, 30, 330, 31))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(330, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(330, 16777215))
        self.lineEdit_3.setStyleSheet("font: 11pt \"Ubuntu Mono\";")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(570, 70, 330, 31))
        self.lineEdit_4.setMinimumSize(QtCore.QSize(330, 0))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(330, 16777215))
        self.lineEdit_4.setStyleSheet("font: 11pt \"Ubuntu Mono\";")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(290, 70, 270, 31))
        self.lineEdit_5.setMinimumSize(QtCore.QSize(270, 0))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(270, 16777215))
        self.lineEdit_5.setStyleSheet("font: 12pt \"Ubuntu Mono\";")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(910, 30, 270, 31))
        self.pushButton_5.setStyleSheet("font: 11pt \"Ubuntu Mono\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_11.setGeometry(QtCore.QRect(910, 70, 281, 31))
        self.lineEdit_11.setStyleSheet("font: 11pt \"Ubuntu Mono\";\n"
"border:none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 150, 1191, 71))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 30, 551, 31))
        self.lineEdit_6.setMinimumSize(QtCore.QSize(270, 0))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(15555555, 16777215))
        self.lineEdit_6.setStyleSheet("font: 12pt \"Ubuntu Mono\";")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(910, 30, 281, 31))
        self.lineEdit_7.setStyleSheet("font: 11pt \"Ubuntu Mono\";\n"
"border:none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(570, 30, 331, 31))
        self.pushButton_6.setStyleSheet("font: 11pt \"Ubuntu Mono\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 230, 1191, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 30, 361, 31))
        self.lineEdit_8.setMinimumSize(QtCore.QSize(270, 0))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(16666666, 16777215))
        self.lineEdit_8.setStyleSheet("font: 12pt \"Ubuntu Mono\";")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(380, 30, 281, 31))
        self.lineEdit_9.setMinimumSize(QtCore.QSize(270, 0))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(16666666, 16777215))
        self.lineEdit_9.setStyleSheet("font: 12pt \"Ubuntu Mono\";")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(670, 30, 231, 31))
        self.pushButton_7.setStyleSheet("font: 11pt \"Ubuntu Mono\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(910, 30, 281, 31))
        self.lineEdit_10.setStyleSheet("font: 11pt \"Ubuntu Mono\";\n"
"border:none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(13, 0, 1181, 31))
        self.label_7.setObjectName("label_7")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_11.addWidget(self.scrollArea)
        self.verticalLayout_10.addWidget(self.frame_10)
        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout_7.addWidget(self.stackedWidget)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_13.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_12 = QtWidgets.QFrame(self.tab_9)
        self.frame_12.setMinimumSize(QtCore.QSize(1021, 42))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frame_12.setStyleSheet("QFrame {\n"
"border: 2px solid #1E90FF;;\n"
"border-radius: 6px;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_12.setContentsMargins(2, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(3)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_8.setMinimumSize(QtCore.QSize(270, 35))
        self.pushButton_8.setMaximumSize(QtCore.QSize(270, 35))
        self.pushButton_8.setStyleSheet("font: 11pt \"Ubuntu Mono\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_12.addWidget(self.pushButton_8)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_12.setStyleSheet("font: 11pt \"Ubuntu Mono\";\n"
"border:none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_12.addWidget(self.lineEdit_12)
        self.verticalLayout_13.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.tab_9)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 164))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 164))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_14)
        self.tableWidget_3.setMinimumSize(QtCore.QSize(1011, 161))
        self.tableWidget_3.setMaximumSize(QtCore.QSize(16777215, 161))
        self.tableWidget_3.setStyleSheet("font-size: 16pt;")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(7)
        self.tableWidget_3.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_3.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_3.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_3.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_3.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_3.setItem(0, 6, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(129)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(129)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(80)
        self.tableWidget_3.verticalHeader().setMinimumSectionSize(80)
        self.horizontalLayout_13.addWidget(self.tableWidget_3)
        self.verticalLayout_14.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_14.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_14.setSpacing(5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setMinimumSize(QtCore.QSize(272, 0))
        self.frame_16.setMaximumSize(QtCore.QSize(272, 16777215))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_9.setMinimumSize(QtCore.QSize(270, 35))
        self.pushButton_9.setMaximumSize(QtCore.QSize(270, 35))
        self.pushButton_9.setStyleSheet("font: 11pt \"Ubuntu Mono\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_15.addWidget(self.pushButton_9)
        self.listWidget_2 = QtWidgets.QListWidget(self.frame_16)
        self.listWidget_2.setStyleSheet("font: 12pt \"Ubuntu Mono\";")
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.verticalLayout_15.addWidget(self.listWidget_2)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_10.setStyleSheet("font: 11pt \"Ubuntu Mono\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_15.addWidget(self.pushButton_10)
        self.horizontalLayout_14.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setStyleSheet("QFrame {\n"
"border: 2px solid #1E90FF;\n"
"border-radius: 6px;\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_15.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_5 = QtWidgets.QWidget(self.frame_17)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_15.addWidget(self.widget_5)
        self.horizontalLayout_14.addWidget(self.frame_17)
        self.verticalLayout_14.addWidget(self.frame_15)
        self.verticalLayout_13.addWidget(self.frame_13)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab_11)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_11)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.tab_12)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_12)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1019, 697))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_21 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.groupBox_10 = QtWidgets.QGroupBox(self.frame_21)
        self.groupBox_10.setMinimumSize(QtCore.QSize(490, 360))
        self.groupBox_10.setStyleSheet("font-size:16px;")
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_22.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_22.setSpacing(6)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_16 = QtWidgets.QLabel(self.groupBox_10)
        self.label_16.setStyleSheet("font-weight: bold;")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_22.addWidget(self.label_16)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_21.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QLineEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.verticalLayout_22.addWidget(self.lineEdit_21)
        self.label_17 = QtWidgets.QLabel(self.groupBox_10)
        self.label_17.setStyleSheet("font-weight: bold;")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_22.addWidget(self.label_17)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_22.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QLineEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout_22.addWidget(self.lineEdit_22)
        self.label_39 = QtWidgets.QLabel(self.groupBox_10)
        self.label_39.setStyleSheet("font-weight: bold;")
        self.label_39.setObjectName("label_39")
        self.verticalLayout_22.addWidget(self.label_39)
        self.comboBox_15 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_15.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.verticalLayout_22.addWidget(self.comboBox_15)
        self.label_40 = QtWidgets.QLabel(self.groupBox_10)
        self.label_40.setStyleSheet("font-weight: bold;")
        self.label_40.setObjectName("label_40")
        self.verticalLayout_22.addWidget(self.label_40)
        self.comboBox_16 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_16.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.verticalLayout_22.addWidget(self.comboBox_16)
        self.label_46 = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("font-weight: bold;")
        self.label_46.setObjectName("label_46")
        self.verticalLayout_22.addWidget(self.label_46)
        self.label_45 = QtWidgets.QLabel(self.groupBox_10)
        self.label_45.setMinimumSize(QtCore.QSize(0, 32))
        self.label_45.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #aa0000;\n"
"    font-size: 20px;\n"
"}")
        self.label_45.setObjectName("label_45")
        self.verticalLayout_22.addWidget(self.label_45)
        self.pushButton_53 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_53.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_53.setStyleSheet("")
        self.pushButton_53.setObjectName("pushButton_53")
        self.verticalLayout_22.addWidget(self.pushButton_53)
        self.horizontalLayout_20.addWidget(self.groupBox_10)
        self.groupBox_9 = QtWidgets.QGroupBox(self.frame_21)
        self.groupBox_9.setMinimumSize(QtCore.QSize(490, 360))
        self.groupBox_9.setStyleSheet("font-size:16px;")
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_21.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_32 = QtWidgets.QLabel(self.groupBox_9)
        self.label_32.setStyleSheet("font-weight: bold;")
        self.label_32.setObjectName("label_32")
        self.verticalLayout_21.addWidget(self.label_32)
        self.comboBox_12 = QtWidgets.QComboBox(self.groupBox_9)
        self.comboBox_12.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.verticalLayout_21.addWidget(self.comboBox_12)
        self.label_33 = QtWidgets.QLabel(self.groupBox_9)
        self.label_33.setStyleSheet("font-weight: bold;")
        self.label_33.setObjectName("label_33")
        self.verticalLayout_21.addWidget(self.label_33)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_17.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QLineEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_21.addWidget(self.lineEdit_17)
        self.label_34 = QtWidgets.QLabel(self.groupBox_9)
        self.label_34.setStyleSheet("font-weight: bold;")
        self.label_34.setObjectName("label_34")
        self.verticalLayout_21.addWidget(self.label_34)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_18.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QLineEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_21.addWidget(self.lineEdit_18)
        self.label_35 = QtWidgets.QLabel(self.groupBox_9)
        self.label_35.setStyleSheet("font-weight: bold;")
        self.label_35.setObjectName("label_35")
        self.verticalLayout_21.addWidget(self.label_35)
        self.comboBox_13 = QtWidgets.QComboBox(self.groupBox_9)
        self.comboBox_13.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.verticalLayout_21.addWidget(self.comboBox_13)
        self.label_38 = QtWidgets.QLabel(self.groupBox_9)
        self.label_38.setStyleSheet("font-weight: bold;")
        self.label_38.setObjectName("label_38")
        self.verticalLayout_21.addWidget(self.label_38)
        self.comboBox_14 = QtWidgets.QComboBox(self.groupBox_9)
        self.comboBox_14.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.verticalLayout_21.addWidget(self.comboBox_14)
        self.pushButton_50 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_50.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_50.setStyleSheet("")
        self.pushButton_50.setObjectName("pushButton_50")
        self.verticalLayout_21.addWidget(self.pushButton_50)
        self.horizontalLayout_20.addWidget(self.groupBox_9)
        self.verticalLayout_16.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.groupBox_11 = QtWidgets.QGroupBox(self.frame_22)
        self.groupBox_11.setMinimumSize(QtCore.QSize(490, 130))
        self.groupBox_11.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_11.setStyleSheet("font-size:16px;")
        self.groupBox_11.setObjectName("groupBox_11")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_11)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_42 = QtWidgets.QLabel(self.groupBox_11)
        self.label_42.setStyleSheet("")
        self.label_42.setObjectName("label_42")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.groupBox_11)
        self.plainTextEdit_6.setMinimumSize(QtCore.QSize(400, 0))
        self.plainTextEdit_6.setStyleSheet("QPlainTextEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QPlainTextEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QPlainTextEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.plainTextEdit_6.setReadOnly(True)
        self.plainTextEdit_6.setPlainText("")
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.plainTextEdit_6)
        self.pushButton_56 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_56.setMinimumSize(QtCore.QSize(200, 35))
        self.pushButton_56.setMaximumSize(QtCore.QSize(16777215, 35))
        self.pushButton_56.setStyleSheet("")
        self.pushButton_56.setObjectName("pushButton_56")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_56)
        self.pushButton_57 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_57.setMinimumSize(QtCore.QSize(200, 35))
        self.pushButton_57.setMaximumSize(QtCore.QSize(16777215, 35))
        self.pushButton_57.setStyleSheet("")
        self.pushButton_57.setObjectName("pushButton_57")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_57)
        self.horizontalLayout_21.addWidget(self.groupBox_11)
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_22)
        self.groupBox_8.setMinimumSize(QtCore.QSize(490, 130))
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_8.setStyleSheet("font-size:16px;")
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_41 = QtWidgets.QLabel(self.groupBox_8)
        self.label_41.setStyleSheet("")
        self.label_41.setObjectName("label_41")
        self.verticalLayout_18.addWidget(self.label_41)
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.groupBox_8)
        self.plainTextEdit_5.setMinimumSize(QtCore.QSize(400, 0))
        self.plainTextEdit_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plainTextEdit_5.setStyleSheet("QPlainTextEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QPlainTextEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QPlainTextEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.plainTextEdit_5.setReadOnly(True)
        self.plainTextEdit_5.setPlainText("")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.verticalLayout_18.addWidget(self.plainTextEdit_5)
        self.pushButton_55 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_55.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_55.setMaximumSize(QtCore.QSize(16777215, 35))
        self.pushButton_55.setStyleSheet("")
        self.pushButton_55.setObjectName("pushButton_55")
        self.verticalLayout_18.addWidget(self.pushButton_55)
        self.horizontalLayout_21.addWidget(self.groupBox_8)
        self.verticalLayout_16.addWidget(self.frame_22)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setMinimumSize(QtCore.QSize(890, 70))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 70))
        self.groupBox_4.setStyleSheet("font-size:16px;")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_18.setContentsMargins(3, 3, 3, 8)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.line_4 = QtWidgets.QFrame(self.groupBox_4)
        self.line_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_18.addWidget(self.line_4)
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setStyleSheet("font-weight: bold;")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_18.addWidget(self.label_29)
        self.pushButton_51 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_51.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_51.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_51.setStyleSheet("")
        self.pushButton_51.setObjectName("pushButton_51")
        self.horizontalLayout_18.addWidget(self.pushButton_51)
        self.line = QtWidgets.QFrame(self.groupBox_4)
        self.line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_18.addWidget(self.line)
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setStyleSheet("font-weight: bold;")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_18.addWidget(self.label_24)
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_7.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_7)
        self.line_2 = QtWidgets.QFrame(self.groupBox_4)
        self.line_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_18.addWidget(self.line_2)
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setStyleSheet("font-weight: bold;")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_18.addWidget(self.label_21)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_6.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.comboBox_6.setEditable(False)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_6)
        self.line_3 = QtWidgets.QFrame(self.groupBox_4)
        self.line_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_18.addWidget(self.line_3)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setStyleSheet("font-weight: bold;")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_18.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_23.setStyleSheet("")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_18.addWidget(self.label_23)
        self.line_5 = QtWidgets.QFrame(self.groupBox_4)
        self.line_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_18.addWidget(self.line_5)
        self.verticalLayout_16.addWidget(self.groupBox_4)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_17.addWidget(self.scrollArea_2)
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_13)
        self.verticalLayout_17.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_17.setSpacing(5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_18 = QtWidgets.QFrame(self.tab_13)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_18.setStyleSheet("font-size:16px;")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        self.frame_20.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_30 = QtWidgets.QLabel(self.frame_20)
        self.label_30.setStyleSheet("")
        self.label_30.setObjectName("label_30")
        self.verticalLayout_20.addWidget(self.label_30)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_20)
        self.lineEdit_20.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QLineEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_20.addWidget(self.lineEdit_20)
        self.label_31 = QtWidgets.QLabel(self.frame_20)
        self.label_31.setStyleSheet("")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_20.addWidget(self.label_31)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.frame_20)
        self.lineEdit_19.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QLineEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.lineEdit_19.setText("")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_20.addWidget(self.lineEdit_19)
        self.pushButton_52 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_52.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_52.setStyleSheet("")
        self.pushButton_52.setObjectName("pushButton_52")
        self.verticalLayout_20.addWidget(self.pushButton_52)
        self.label_8 = QtWidgets.QLabel(self.frame_20)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_20.addWidget(self.label_8)
        self.horizontalLayout_19.addWidget(self.frame_20)
        self.listWidget_3 = QtWidgets.QListWidget(self.frame_18)
        self.listWidget_3.setStyleSheet("QListWidget {\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: lightblue;\n"
"}\n"
"")
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.horizontalLayout_19.addWidget(self.listWidget_3)
        self.verticalLayout_17.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.tab_13)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_6 = QtWidgets.QWidget(self.frame_19)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout.addWidget(self.widget_6, 0, 0, 1, 1)
        self.verticalLayout_17.addWidget(self.frame_19)
        self.tabWidget_4.addTab(self.tab_13, "")
        self.horizontalLayout_16.addWidget(self.tabWidget_4)
        self.tabWidget.addTab(self.tab_11, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PipeAnalysis"))
        self.pushButton.setText(_translate("MainWindow", "Загрузить файл инспекции"))
        self.label_2.setText(_translate("MainWindow", "Сведения о трубопроводе"))
        self.listWidget.setSortingEnabled(False)
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Название:"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "\n"
"Длина трубопровода:"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "\n"
"Диаметр трубопровода:"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "\n"
"Диапазон толщины стенки:"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "\n"
"Превалирующий тип сварного шва:"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "\n"
"Мин. радиус изгиба колена:"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "\n"
"Марка стали:"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "\n"
"Условия во время нормального режима:\n"
"• Давление:\n"
"• Температура:\n"
"• Среда:\n"
"• Скорость потока среды:"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "\n"
"Условия во время инспекции:\n"
"• Давление:\n"
"• Температура:\n"
"• Контактная среда:\n"
"• Скорость звука в контактной среде: \n"
"• Затухание в контактной среде:\n"
"• Скорость инспекции (средняя):"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "№ попер.\n"
"св. шва"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Абсол.\n"
"расст."))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Контр./\n"
"секция\n"
"толщ. ст"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Остат.\n"
"толщ. ст."))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Глубина\n"
"дефекта"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Тип характ.\n"
"особ."))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "-"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Толщина стенки"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Потери металла"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "2D"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "3D (В разработке)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Газопровод"))
        self.label_3.setText(_translate("MainWindow", "Подробная информация"))
        self.pushButton_2.setText(_translate("MainWindow", "->"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Попер.\n"
"св. шва"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID х.о./\n"
"маркера"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Абсол.\n"
"расст.\n"
"[м]"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Расст. до\n"
"шва вверх\n"
"по ходу\n"
"[м]"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Полож.\n"
"по\n"
"окруж.\n"
"[°]"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Контр./\n"
"секция\n"
"толщ. ст.\n"
"[мм]"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Остат.\n"
"толщ.\n"
"ст.\n"
"[мм]"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Глубина\n"
"[мм]"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Глубина\n"
"[%]"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Длина\n"
"секции\n"
"[м]"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Длина\n"
"[мм]"))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Ширина\n"
"[мм]"))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Тип\n"
"характ.\n"
"особ."))
        item = self.tableWidget_2.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Подтип"))
        item = self.tableWidget_2.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Примечание"))
        item = self.tableWidget_2.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Отн.\n"
"пол."))
        item = self.tableWidget_2.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Полож.\n"
"в стенке"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "Графическое представление"))
        self.pushButton_3.setText(_translate("MainWindow", "->"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "."))
        self.comboBox.setItemText(0, _translate("MainWindow", "-"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Толщина стенки 360°"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "-"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Объемная модель трубы"))
        self.label_5.setText(_translate("MainWindow", "Выявление дефектов на секции"))
        self.pushButton_4.setText(_translate("MainWindow", "->"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "-"))
        self.groupBox.setTitle(_translate("MainWindow", "Нахождение максимальной глубины дефекта"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Толщина стенки секции"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Рабочее давление МПа (бар/10)"))
        self.label_6.setText(_translate("MainWindow", "Категория участка: "))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "B"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "I и II"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "III и IV"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Время работы с момента ввода в эксплуатацию "))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Срок безопасной эксплуатации трубы"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Коэффициент Фолиаса"))
        self.pushButton_5.setText(_translate("MainWindow", "Рассчитать"))
        self.lineEdit_11.setText(_translate("MainWindow", "Максимальная глубина:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Коэффицент Фолиаса"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Коэффицент трубы в диапазоне (1.31, 1.61). Обычно 1.32 или 1.61"))
        self.lineEdit_7.setText(_translate("MainWindow", "Коэффицент Фолиаса:"))
        self.pushButton_6.setText(_translate("MainWindow", "Рассчитать"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Напряжение течения"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "Время работы с момента ввода в эксплуатацию "))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "Срок безопасной эксплуатации трубы"))
        self.pushButton_7.setText(_translate("MainWindow", "Рассчитать"))
        self.lineEdit_10.setText(_translate("MainWindow", "Напряжение течения:"))
        self.label_7.setText(_translate("MainWindow", "Определенный тип дефекта: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Секции"))
        self.pushButton_8.setText(_translate("MainWindow", "Рассчитать"))
        self.lineEdit_12.setText(_translate("MainWindow", "Суммарная приведенная длина дефектов:"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Значения"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Полож.\n"
"по окруж.\n"
"[°]"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Толщ.\n"
"стенки [мм]"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Остат. толщ.\n"
"стенки [мм]"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Глубина\n"
"[мм]"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Глубина\n"
"[%]"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Длина\n"
"[мм]"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ширина\n"
"[мм]"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.pushButton_9.setText(_translate("MainWindow", "Использовать нейросеть"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "1. Cвяз. с производством\n"
"(Потеря металла)\n"
"0.0"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "2. Отложения\n"
"(Геометрия)\n"
"0.0"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "3. Внешние воздействия\n"
"(Потеря металла)\n"
"0.0"))
        item = self.listWidget_2.item(3)
        item.setText(_translate("MainWindow", "4. Действия человека\n"
"(Изменение толщ. ст.)\n"
"0.0"))
        item = self.listWidget_2.item(4)
        item.setText(_translate("MainWindow", "5. Нет особенностей\n"
"(Дефектов не обнаружено)\n"
"0.0"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButton_10.setText(_translate("MainWindow", "Загрузить модель"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Нейросеть"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Основная настройка"))
        self.label_16.setText(_translate("MainWindow", "Количество входных параметров"))
        self.lineEdit_21.setPlaceholderText(_translate("MainWindow", "10"))
        self.label_17.setText(_translate("MainWindow", "Количество выходных параметров"))
        self.lineEdit_22.setPlaceholderText(_translate("MainWindow", "10"))
        self.label_39.setText(_translate("MainWindow", "Выбор функции оптимизации"))
        self.comboBox_15.setItemText(0, _translate("MainWindow", "Adam"))
        self.comboBox_15.setItemText(1, _translate("MainWindow", "SGD"))
        self.label_40.setText(_translate("MainWindow", "Количество слоёв"))
        self.comboBox_16.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_16.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_16.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_16.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_16.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_16.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_16.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_16.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_16.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_16.setItemText(9, _translate("MainWindow", "10"))
        self.label_46.setText(_translate("MainWindow", "Наличие модели"))
        self.label_45.setText(_translate("MainWindow", "Нет"))
        self.pushButton_53.setText(_translate("MainWindow", "Создать модель"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Информация о слое"))
        self.label_32.setText(_translate("MainWindow", "Номер слоя"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "1"))
        self.label_33.setText(_translate("MainWindow", "Количество входных параметров"))
        self.lineEdit_17.setPlaceholderText(_translate("MainWindow", "10"))
        self.label_34.setText(_translate("MainWindow", "Количество выходных параметров"))
        self.lineEdit_18.setPlaceholderText(_translate("MainWindow", "10"))
        self.label_35.setText(_translate("MainWindow", "Тип слоя"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "FC"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "RNN"))
        self.comboBox_13.setItemText(2, _translate("MainWindow", "LSTM"))
        self.comboBox_13.setItemText(3, _translate("MainWindow", "GRU"))
        self.label_38.setText(_translate("MainWindow", "Функция активации"))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "Sigmoid"))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "ReLU"))
        self.comboBox_14.setItemText(2, _translate("MainWindow", "Tanh"))
        self.comboBox_14.setItemText(3, _translate("MainWindow", "Softmax"))
        self.pushButton_50.setText(_translate("MainWindow", "Сохранить слой"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Загрузка/Сохранение модели"))
        self.label_42.setText(_translate("MainWindow", "Путь:"))
        self.plainTextEdit_6.setPlaceholderText(_translate("MainWindow", "Здесь будет путь до вашей модели"))
        self.pushButton_56.setText(_translate("MainWindow", "Сохранить"))
        self.pushButton_57.setText(_translate("MainWindow", "Загрузить"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Загрузка базы для обучения"))
        self.label_41.setText(_translate("MainWindow", "Путь:"))
        self.plainTextEdit_5.setPlaceholderText(_translate("MainWindow", "Здесь будет путь до вашей базы"))
        self.pushButton_55.setText(_translate("MainWindow", "Выберите путь"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Дополнительная настройка"))
        self.label_29.setText(_translate("MainWindow", "Сохранить модель:"))
        self.pushButton_51.setText(_translate("MainWindow", "Сохранить модель"))
        self.label_24.setText(_translate("MainWindow", "Обучение:"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "CPU"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "CUDA"))
        self.label_21.setText(_translate("MainWindow", "Работа слоёв:"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "CPU"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "CUDA"))
        self.label_22.setText(_translate("MainWindow", "Наличие CUDA:"))
        self.label_23.setText(_translate("MainWindow", "True"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("MainWindow", "Настройка"))
        self.label_30.setText(_translate("MainWindow", "Количество эпох:"))
        self.lineEdit_20.setPlaceholderText(_translate("MainWindow", "10"))
        self.label_31.setText(_translate("MainWindow", "Коэфицент скорости обучения:"))
        self.lineEdit_19.setPlaceholderText(_translate("MainWindow", "0.0001"))
        self.pushButton_52.setText(_translate("MainWindow", "Начать обучение"))
        self.label_8.setText(_translate("MainWindow", "Среднеквадратичная: 0.04794\n"
"Точность: 93%"))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("MainWindow", "Новый элемент"))
        item = self.listWidget_3.item(1)
        item.setText(_translate("MainWindow", "Новый элемент"))
        item = self.listWidget_3.item(2)
        item.setText(_translate("MainWindow", "Новый элемент"))
        item = self.listWidget_3.item(3)
        item.setText(_translate("MainWindow", "Новый элемент"))
        item = self.listWidget_3.item(4)
        item.setText(_translate("MainWindow", "Новый элемент"))
        item = self.listWidget_3.item(5)
        item.setText(_translate("MainWindow", "Новый элемент"))
        item = self.listWidget_3.item(6)
        item.setText(_translate("MainWindow", "Новый элемент"))
        item = self.listWidget_3.item(7)
        item.setText(_translate("MainWindow", "Новый элемент"))
        item = self.listWidget_3.item(8)
        item.setText(_translate("MainWindow", "Новый элемент"))
        item = self.listWidget_3.item(9)
        item.setText(_translate("MainWindow", "Новый элемент"))
        item = self.listWidget_3.item(10)
        item.setText(_translate("MainWindow", "22: MSE: 0.06721"))
        item = self.listWidget_3.item(11)
        item.setText(_translate("MainWindow", "23: MSE: 0.06573"))
        item = self.listWidget_3.item(12)
        item.setText(_translate("MainWindow", "24: MSE: 0.06123"))
        item = self.listWidget_3.item(13)
        item.setText(_translate("MainWindow", "25: MSE: 0.05754"))
        item = self.listWidget_3.item(14)
        item.setText(_translate("MainWindow", "26: MSE: 0.04998"))
        item = self.listWidget_3.item(15)
        item.setText(_translate("MainWindow", "27: MSE: 0.04921"))
        item = self.listWidget_3.item(16)
        item.setText(_translate("MainWindow", "28: MSE: 0.04864"))
        item = self.listWidget_3.item(17)
        item.setText(_translate("MainWindow", "29: MSE: 0.04834"))
        item = self.listWidget_3.item(18)
        item.setText(_translate("MainWindow", "30: MSE: 0.04794"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("MainWindow", "Обучение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Конструктор"))
